CREATE DATABASE JSANCHEZDIGIPRO;
USE JSANCHEZDIGIPRO;
GO

CREATE TABLE ALUMNO
(
IDALUMNO INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE VARCHAR(50),
APELLIDOPATERNO VARCHAR(50),
APELLIDOMATERNO VARCHAR(50)
)
GO

CREATE TABLE MATERIA
(
IDMATERIA INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE VARCHAR(50),
COSTO DECIMAL
)
GO

CREATE TABLE ALUMNOMATERIA
(
IDALUMNOMATERIA INT IDENTITY(1,1) PRIMARY KEY,
IDALUMNO INT,
IDMATERIA INT,
CONSTRAINT FK_ALUMNOMATERIA_ALUMNO FOREIGN KEY (IDALUMNO) REFERENCES ALUMNO (IDALUMNO),
CONSTRAINT FK_ALUMNOMATERIA_MATERIA FOREIGN KEY (IDMATERIA) REFERENCES MATERIA (IDMATERIA)
)
GO

CREATE PROCEDURE AlumnoAdd
@NOMBRE VARCHAR(50),
@APELLIDOPATERNO VARCHAR(50),
@APELLIDOMATERNO VARCHAR(50)
AS
INSERT INTO ALUMNO(NOMBRE,APELLIDOPATERNO,APELLIDOMATERNO)
VALUES(@NOMBRE,@APELLIDOPATERNO,@APELLIDOMATERNO)
GO

CREATE PROCEDURE AlumnoUpdate
@IDALUMNO INT,
@NOMBRE VARCHAR(50),
@APELLIDOPATERNO VARCHAR(50),
@APELLIDOMATERNO VARCHAR(50)
AS
UPDATE ALUMNO SET NOMBRE=@NOMBRE, APELLIDOPATERNO=@APELLIDOPATERNO, APELLIDOMATERNO=@APELLIDOMATERNO WHERE IDALUMNO = @IDALUMNO
GO

CREATE PROCEDURE AlumnoDelete
@IDALUMNO INT
AS
DELETE FROM ALUMNO WHERE IDALUMNO = @IDALUMNO
GO

CREATE PROCEDURE AlumnoGetById
@IDALUMNO INT
AS
SELECT IDALUMNO,NOMBRE,APELLIDOPATERNO,APELLIDOMATERNO FROM ALUMNO WHERE IDALUMNO = @IDALUMNO
GO

CREATE PROCEDURE AlumnoGetAll
AS
SELECT IDALUMNO,NOMBRE,APELLIDOPATERNO,APELLIDOMATERNO FROM ALUMNO
GO

CREATE PROCEDURE MateriaAdd
@NOMBRE VARCHAR(50),
@COSTO DECIMAL
AS
INSERT INTO MATERIA(NOMBRE,COSTO)VALUES(@NOMBRE,@COSTO)
GO

CREATE PROCEDURE MateriaUpdate
@IDMATERIA INT,
@NOMBRE VARCHAR(50),
@COSTO DECIMAL
AS
UPDATE MATERIA SET NOMBRE=@NOMBRE,COSTO=@COSTO WHERE IDMATERIA=@IDMATERIA
GO

CREATE PROCEDURE MateriaDelete
@IDMATERIA INT
AS
DELETE FROM MATERIA WHERE IDMATERIA=@IDMATERIA
GO

CREATE PROCEDURE MateriaGetById
@IDMATERIA INT
AS
SELECT IDMATERIA,NOMBRE,COSTO FROM MATERIA WHERE IDMATERIA=@IDMATERIA
GO

CREATE PROCEDURE MateriaGetAll
AS
SELECT IDMATERIA,NOMBRE,COSTO FROM MATERIA
GO

CREATE PROCEDURE AlumnoMateriaAdd
@IDALUMNO INT,
@IDMATERIA INT
AS
INSERT INTO ALUMNOMATERIA(IDALUMNO,IDMATERIA)VALUES(@IDALUMNO,@IDMATERIA)
GO

CREATE PROCEDURE AlumnoMateriaUpdate
@IDALUMNOMATERIA INT,
@IDALUMNO INT,
@IDMATERIA INT
AS
UPDATE ALUMNOMATERIA SET IDALUMNO=@IDALUMNO, IDMATERIA=@IDMATERIA WHERE IDALUMNOMATERIA = @IDALUMNOMATERIA
GO

CREATE PROCEDURE AlumnoMateriaDelete
@IDALUMNOMATERIA INT
AS
DELETE FROM ALUMNOMATERIA WHERE IDALUMNOMATERIA=@IDALUMNOMATERIA
GO

CREATE PROCEDURE AlumnoMateriaGetById
@IDALUMNOMATERIA INT
AS
SELECT IDALUMNOMATERIA,A.NOMBRE AS NOMBRE_ALUMNO, A.APELLIDOPATERNO,A.APELLIDOMATERNO,M.NOMBRE AS NOMBRE_MATERIA,M.COSTO FROM ALUMNOMATERIA AM
INNER JOIN ALUMNO A ON A.IDALUMNO = AM.IDALUMNO
INNER JOIN MATERIA M ON M.IDMATERIA = AM.IDMATERIA 
WHERE IDALUMNOMATERIA=@IDALUMNOMATERIA
GO

CREATE PROCEDURE AlumnoMateriaGetAll
@IDALUMNO INT
AS
SELECT AM.IDALUMNOMATERIA,A.IDALUMNO,A.NOMBRE,A.APELLIDOPATERNO,A.APELLIDOMATERNO,M.IDMATERIA,M.NOMBRE,M.COSTO FROM ALUMNOMATERIA AM
INNER JOIN MATERIA M ON M.IDMATERIA = AM.IDMATERIA
INNER JOIN ALUMNO A ON A.IDALUMNO = AM.IDALUMNO
WHERE A.IDALUMNO=@IDALUMNO
GO

CREATE PROCEDURE AlumnoMateriasDisponibles
@IDALUMNO INT
AS
SELECT M.IDMATERIA,M.NOMBRE, M.COSTO FROM ALUMNOMATERIA AM
INNER JOIN MATERIA M ON M.IDMATERIA = AM.IDMATERIA
WHERE M.IDMATERIA NOT IN(SELECT AM.IDMATERIA FROM AlumnoMateria AM WHERE AM.IDALUMNO=@IDALUMNO)
GO

ALTER PROCEDURE AlumnoMateriasDisponibles
@IDALUMNO INT
AS
SELECT M.IDMATERIA,M.NOMBRE, M.COSTO FROM MATERIA M
LEFT JOIN ALUMNOMATERIA AM ON M.IDMATERIA = AM.IDMATERIA AND AM.IDALUMNO = @IDALUMNO
WHERE AM.IDALUMNO IS NULL
GO