//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JSANCHEZDIGIPROEntities : DbContext
    {
        public JSANCHEZDIGIPROEntities()
            : base("name=JSANCHEZDIGIPROEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALUMNO> ALUMNO { get; set; }
        public virtual DbSet<ALUMNOMATERIA> ALUMNOMATERIA { get; set; }
        public virtual DbSet<MATERIA> MATERIA { get; set; }
    
        public virtual int AlumnoAdd(string nOMBRE, string aPELLIDOPATERNO, string aPELLIDOMATERNO)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDOPATERNOParameter = aPELLIDOPATERNO != null ?
                new ObjectParameter("APELLIDOPATERNO", aPELLIDOPATERNO) :
                new ObjectParameter("APELLIDOPATERNO", typeof(string));
    
            var aPELLIDOMATERNOParameter = aPELLIDOMATERNO != null ?
                new ObjectParameter("APELLIDOMATERNO", aPELLIDOMATERNO) :
                new ObjectParameter("APELLIDOMATERNO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AlumnoAdd", nOMBREParameter, aPELLIDOPATERNOParameter, aPELLIDOMATERNOParameter);
        }
    
        public virtual int AlumnoDelete(Nullable<int> iDALUMNO)
        {
            var iDALUMNOParameter = iDALUMNO.HasValue ?
                new ObjectParameter("IDALUMNO", iDALUMNO) :
                new ObjectParameter("IDALUMNO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AlumnoDelete", iDALUMNOParameter);
        }
    
        public virtual ObjectResult<AlumnoGetAll_Result> AlumnoGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AlumnoGetAll_Result>("AlumnoGetAll");
        }
    
        public virtual ObjectResult<AlumnoGetById_Result> AlumnoGetById(Nullable<int> iDALUMNO)
        {
            var iDALUMNOParameter = iDALUMNO.HasValue ?
                new ObjectParameter("IDALUMNO", iDALUMNO) :
                new ObjectParameter("IDALUMNO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AlumnoGetById_Result>("AlumnoGetById", iDALUMNOParameter);
        }
    
        public virtual int AlumnoMateriaAdd(Nullable<int> iDALUMNO, Nullable<int> iDMATERIA)
        {
            var iDALUMNOParameter = iDALUMNO.HasValue ?
                new ObjectParameter("IDALUMNO", iDALUMNO) :
                new ObjectParameter("IDALUMNO", typeof(int));
    
            var iDMATERIAParameter = iDMATERIA.HasValue ?
                new ObjectParameter("IDMATERIA", iDMATERIA) :
                new ObjectParameter("IDMATERIA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AlumnoMateriaAdd", iDALUMNOParameter, iDMATERIAParameter);
        }
    
        public virtual int AlumnoMateriaDelete(Nullable<int> iDALUMNOMATERIA)
        {
            var iDALUMNOMATERIAParameter = iDALUMNOMATERIA.HasValue ?
                new ObjectParameter("IDALUMNOMATERIA", iDALUMNOMATERIA) :
                new ObjectParameter("IDALUMNOMATERIA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AlumnoMateriaDelete", iDALUMNOMATERIAParameter);
        }
    
        public virtual ObjectResult<AlumnoMateriaGetAll_Result> AlumnoMateriaGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AlumnoMateriaGetAll_Result>("AlumnoMateriaGetAll");
        }
    
        public virtual ObjectResult<AlumnoMateriaGetById_Result> AlumnoMateriaGetById(Nullable<int> iDALUMNOMATERIA)
        {
            var iDALUMNOMATERIAParameter = iDALUMNOMATERIA.HasValue ?
                new ObjectParameter("IDALUMNOMATERIA", iDALUMNOMATERIA) :
                new ObjectParameter("IDALUMNOMATERIA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AlumnoMateriaGetById_Result>("AlumnoMateriaGetById", iDALUMNOMATERIAParameter);
        }
    
        public virtual int AlumnoMateriaUpdate(Nullable<int> iDALUMNOMATERIA, Nullable<int> iDALUMNO, Nullable<int> iDMATERIA)
        {
            var iDALUMNOMATERIAParameter = iDALUMNOMATERIA.HasValue ?
                new ObjectParameter("IDALUMNOMATERIA", iDALUMNOMATERIA) :
                new ObjectParameter("IDALUMNOMATERIA", typeof(int));
    
            var iDALUMNOParameter = iDALUMNO.HasValue ?
                new ObjectParameter("IDALUMNO", iDALUMNO) :
                new ObjectParameter("IDALUMNO", typeof(int));
    
            var iDMATERIAParameter = iDMATERIA.HasValue ?
                new ObjectParameter("IDMATERIA", iDMATERIA) :
                new ObjectParameter("IDMATERIA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AlumnoMateriaUpdate", iDALUMNOMATERIAParameter, iDALUMNOParameter, iDMATERIAParameter);
        }
    
        public virtual int AlumnoUpdate(Nullable<int> iDALUMNO, string nOMBRE, string aPELLIDOPATERNO, string aPELLIDOMATERNO)
        {
            var iDALUMNOParameter = iDALUMNO.HasValue ?
                new ObjectParameter("IDALUMNO", iDALUMNO) :
                new ObjectParameter("IDALUMNO", typeof(int));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDOPATERNOParameter = aPELLIDOPATERNO != null ?
                new ObjectParameter("APELLIDOPATERNO", aPELLIDOPATERNO) :
                new ObjectParameter("APELLIDOPATERNO", typeof(string));
    
            var aPELLIDOMATERNOParameter = aPELLIDOMATERNO != null ?
                new ObjectParameter("APELLIDOMATERNO", aPELLIDOMATERNO) :
                new ObjectParameter("APELLIDOMATERNO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AlumnoUpdate", iDALUMNOParameter, nOMBREParameter, aPELLIDOPATERNOParameter, aPELLIDOMATERNOParameter);
        }
    
        public virtual int MateriaAdd(string nOMBRE, Nullable<decimal> cOSTO)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var cOSTOParameter = cOSTO.HasValue ?
                new ObjectParameter("COSTO", cOSTO) :
                new ObjectParameter("COSTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MateriaAdd", nOMBREParameter, cOSTOParameter);
        }
    
        public virtual int MateriaDelete(Nullable<int> iDMATERIA)
        {
            var iDMATERIAParameter = iDMATERIA.HasValue ?
                new ObjectParameter("IDMATERIA", iDMATERIA) :
                new ObjectParameter("IDMATERIA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MateriaDelete", iDMATERIAParameter);
        }
    
        public virtual ObjectResult<MateriaGetAll_Result> MateriaGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MateriaGetAll_Result>("MateriaGetAll");
        }
    
        public virtual ObjectResult<MateriaGetById_Result> MateriaGetById(Nullable<int> iDMATERIA)
        {
            var iDMATERIAParameter = iDMATERIA.HasValue ?
                new ObjectParameter("IDMATERIA", iDMATERIA) :
                new ObjectParameter("IDMATERIA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MateriaGetById_Result>("MateriaGetById", iDMATERIAParameter);
        }
    
        public virtual int MateriaUpdate(Nullable<int> iDMATERIA, string nOMBRE, Nullable<decimal> cOSTO)
        {
            var iDMATERIAParameter = iDMATERIA.HasValue ?
                new ObjectParameter("IDMATERIA", iDMATERIA) :
                new ObjectParameter("IDMATERIA", typeof(int));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var cOSTOParameter = cOSTO.HasValue ?
                new ObjectParameter("COSTO", cOSTO) :
                new ObjectParameter("COSTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MateriaUpdate", iDMATERIAParameter, nOMBREParameter, cOSTOParameter);
        }
    }
}
